### ISSUE TITLE
Request to change namespace of verification SDK

### ISSUE THREAD

**Issue by PrasshantChavan** [cashfree/cashfree-verification-sdk-php#3]
### Payment gateway SDK and Verification SDK

Both SDKs have the same namespace, so it creates ambiguous class resolutions.
We can't use both SDK's simultaneously.

Please resolve this issue ASAP.

This is the issue:
![image](https://github.com/user-attachments/assets/86606ac4-3469-4ecc-a087-701f4b85b53a)

Because of this issue we can't initiate 2 SDK's at a time.

@suhas-cashfree @harshitprajapati316

**Comment by Harshit-Prajapati-cashfree** [comment]
@PrasshantChavan we have updated the name space.

**Comment by PrasshantChavan** [comment]
@harshitprajapati316  Thanks for the quick response.
